name: bi-monthly Android App Deploy

on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:  # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases

    steps:
      - name: Generate Build Date
        id: date
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build APK
        run: |
          ./gradlew assembleDebug --no-daemon
          mkdir -p artifacts

      - name: Prepare APK for Release
        run: |
          ls
          cp app/build/outputs/apk/foss/debug/*.apk \
          artifacts/clauncher-${{ env.BUILD_DATE }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/clauncher-${{ env.BUILD_DATE }}.apk
          name: "CLauncher bi-monthly Build | ${{ env.BUILD_DATE }}"
          tag_name: "bimonthly-${{ env.BUILD_DATE }}"
          prerelease: true
          body: |
            ## 📱 CLauncher bi-monthly Build
            
            **Build Date**: ${{ env.BUILD_DATE }}
            
            ### 📝 Notes
            - This is an automated bi-monthly build
            
          generate_release_notes: true

      - name: Cleanup Artifacts
        if: always()
        run: rm -rf artifacts/