name: Weekly Android App Deploy

on:
  schedule:
    - cron: '0 0 * * 2'  # Every Tuesday at 00:00 UTC
  workflow_dispatch:  # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases

    steps:
      - name: Generate Build Date
        id: date
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build APK
        run: |
          ./gradlew assembleDebug --no-daemon
          mkdir -p artifacts

      - name: Prepare APK for Release
        run: |
          cp composeApp/build/outputs/apk/foss/debug/app-foss-debug.apk \
          artifacts/clauncher-${{ env.BUILD_DATE }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/clauncher-${{ env.BUILD_DATE }}.apk
          name: "CLauncher Weekly Build | ${{ env.BUILD_DATE }}"
          tag_name: "weekly-${{ env.BUILD_DATE }}"
          prerelease: true
          body: |
            ## 📱 CLauncher Weekly Build
            
            **Build Date**: ${{ env.BUILD_DATE }}
            
            ### 📝 Notes
            - This is an automated weekly build
            - For testing purposes only
            - Please report any issues on the GitHub repository
            
            ### 📲 Installation
            - Download the APK from the assets below
            - Enable "Install from unknown sources" in your Android settings
            - Install the downloaded APK
            
            ### ⚠️ Disclaimer
            This is a development build and may contain bugs. Use at your own risk.
          generate_release_notes: true

      - name: Cleanup Artifacts
        if: always()
        run: rm -rf artifacts/